### ISSUE TITLE
Questions regarding the second part of the anagram question

### ISSUE THREAD

**Issue by SammiXu0** [MIS3640/mis3640#3]
https://github.com/SammiXu0/MIS3640/blob/c8950ef45a320077830289c101760b319ca96914/session14/tup_exercise2.2%262.3.py#L101

Hi Professor: 

I am not sure why my function only returns some of the anagrams and not all of them after I rearranged them in descending order.  I fed the full list of anagrams into the function (from the previous functions). 

Thank you!
Sammi

**Comment by lzblack** [comment]
`ordered_dict[len(i)] = word_dict[i]` means in every iteration, `ordered_dict[len(i)]` is reset to a new word. Instead, you need to use `append`.
